server.port: 8080
spring:
  main:
    allow-circular-references: true
  application:
    name: Project-MyOrg
  datasource:
    url: jdbc:mysql://localhost:3306/project_my_org
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
projectmyorg:
  app:
    jwtSecret: nI3K0HuZiHsX8NlDOoHvUbkUZScg7HiX1fxM7WxC+RM=
    jwtExpirationMs: 86400000
    cors:
      allowedOrigins: http://localhost:3000, http://localhost:4200