spring:
  datasource:
    url: jdbc:h2:file:./data/h2db      #mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      
projectmyorg:
  app:
    jwtSecret: nI3K0HuZiHsX8NlDOoHvUbkUZScg7HiX1fxM7WxC+RM=
    jwtExpirationMs: 86400000
    cors:
      allowedOrigins: http://localhost:3000, http://localhost:4200